#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import time


def update():
    os.system('cd ~/programa')
    os.system('rm backup/firmware.py.backup')   #remove old firmware backup file
    time.sleep(1)
    os.system('rm backup/Sensor.py.backup')     #remove old firmware Sensor file
    os.system('mv firmware.py backup/firmware.py.backup')#move and rename file.py to file.py.backup inside backup folder
    time.sleep(1)
    os.system('mv Sensor.py backup/Sensor.py.backup')    #move and rename file.py to file.py.backup inside backup folder

    time.sleep(1)
    os.system('wget -O firmware.py https://raw.githubusercontent.com/kelvinhenriqu/PressurePackage/main/firmware.py')#download from JT's github the Firmware.py file
    time.sleep(1)
    os.system('wget -O Sensor.py https://raw.githubusercontent.com/kelvinhenriqu/PressurePackage/main/Sensor.py')#download from JT's github the Sensor.py file
    print('successfully updated')
    print('starting main program')
    time.sleep(1)
    os.system('python3 firmware.py')#start program


def checkupdate():
    os.system('cd ~/programa')
    os.system('wget -O Version.txt https://raw.githubusercontent.com/kelvinhenriqu/PressurePackage/main/Version.txt')#download from JT's github the version file

    new_version = ''
    with open('Version.txt', 'r') as f:
        for line in f:
            line = line.strip()
            if '__VERSION__' in line:
                _, new_version = line.split('=', maxsplit=1)
                new_version = new_version.strip()
                break
    print('Server version is:', new_version)


    with open('firmware.py', 'r') as f:
        for line in f:
            line = line.strip()
            if '__VERSION__' in line:
                _, current_version = line.split('=', maxsplit=1)
                current_version = current_version.strip()
                break
    print('Current version is:', current_version)


    if current_version < new_version:
        print('need to update')
        os.system('rm Version.txt')
        update()
    else:
        print("don't neet to update")
        os.system('rm Version.txt')
        print('starting main program')
        os.system('python3 firmware.py')


checkupdate()

